apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orographie-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: orographie
    spec:
      containers:
        - name: orographie
          image: brigittewarner/orographie:firsttry
          ports:
            - containerPort: 8080
          args: ["foreground"]
          env:
            - name: HOST
              value: "example.com"
            - name: SECRET_KEY_BASE
              value: "highlysecretkey"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: DB_NAME
              value: "orographie_dev"
            - name: DB_HOSTNAME
              value: "10.0.2.2"
