apiVersion: v1
kind: Service
metadata:
  name: orographie-service
spec:
  ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: orographie
  type: LoadBalancer
